# Generated by Django 4.2.1 on 2023-09-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_author_about_author_author_author_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
