# Generated by Django 4.2.1 on 2023-09-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
