# Generated by Django 4.2.1 on 2023-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_custommodelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='Phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='postcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='profession',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
