# Generated by Django 4.2.1 on 2023-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_user_course_phone_user_course_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='course',
        ),
        migrations.AddField(
            model_name='user_course',
            name='course',
            field=models.ManyToManyField(to='my_app.course'),
        ),
    ]
