# Generated by Django 4.2.1 on 2023-09-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_remove_user_course_course_user_course_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='Courses',
        ),
        migrations.AddField(
            model_name='user_course',
            name='course',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.course'),
        ),
    ]
