# Generated by Django 4.2.1 on 2023-09-10 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0021_alter_user_course_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('postcode', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
