# Generated by Django 4.2.1 on 2023-09-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_user_course1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Course',
        ),
    ]
