# Generated by Django 4.2.1 on 2023-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_alter_user_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_course',
            old_name='course',
            new_name='Course',
        ),
    ]
