# Generated by Django 4.2.1 on 2023-09-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_remove_user_course_course_user_course_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Course',
        ),
    ]
