# Generated by Django 4.2.1 on 2023-09-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0032_alter_author_about_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='author'),
        ),
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('postcode', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='my_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
