# Generated by Django 4.2.1 on 2023-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_alter_author_author_profile_user_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
