# Generated by Django 4.2.1 on 2023-09-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[(1, 'Not at all Satisfied'), (2, 'Partly Satisfied'), (3, 'Satisfied'), (4, 'More than Satisfied'), (5, 'Very Satisfied')], max_length=100, null=True),
        ),
    ]
